plugin:
  description:
    name: Hydra
    version: 2.01
    description: Edge to protect your server
    authors:
      - Hydra Development
      - RealTrippy
    website: https://www.hydra.rip
  command:
    name: hac
    aliases:
      - hyac
      - ac
      - anticheat
storage:
  method: MONGO
  mongo:
    URI: "mongodb://127.0.0.1"
    database: "Edge"
