package xyz.edge.ac.packetevents.packettype;

public static class Server
{
    public static final byte SPAWN_ENTITY = -67;
    public static final byte SPAWN_ENTITY_EXPERIENCE_ORB = -66;
    public static final byte SPAWN_ENTITY_WEATHER = -65;
    public static final byte SPAWN_ENTITY_LIVING = -64;
    public static final byte SPAWN_ENTITY_PAINTING = -63;
    public static final byte SPAWN_ENTITY_SPAWN = -62;
    public static final byte ANIMATION = -61;
    public static final byte STATISTIC = -60;
    public static final byte BLOCK_BREAK = -59;
    public static final byte BLOCK_BREAK_ANIMATION = -58;
    public static final byte TILE_ENTITY_DATA = -57;
    public static final byte BLOCK_ACTION = -56;
    public static final byte BLOCK_CHANGE = -55;
    public static final byte BOSS = -54;
    public static final byte SERVER_DIFFICULTY = -53;
    public static final byte CHAT = -52;
    public static final byte MULTI_BLOCK_CHANGE = -51;
    public static final byte TAB_COMPLETE = -50;
    public static final byte COMMANDS = -49;
    public static final byte TRANSACTION = -48;
    public static final byte CLOSE_WINDOW = -47;
    public static final byte WINDOW_ITEMS = -46;
    public static final byte WINDOW_DATA = -45;
    public static final byte SET_SLOT = -44;
    public static final byte SET_COOLDOWN = -43;
    public static final byte CUSTOM_PAYLOAD = -42;
    public static final byte CUSTOM_SOUND_EFFECT = -41;
    public static final byte KICK_DISCONNECT = -40;
    public static final byte ENTITY_STATUS = -39;
    public static final byte EXPLOSION = -38;
    public static final byte UNLOAD_CHUNK = -37;
    public static final byte GAME_STATE_CHANGE = -36;
    public static final byte OPEN_WINDOW_HORSE = -35;
    public static final byte KEEP_ALIVE = -34;
    public static final byte MAP_CHUNK = -33;
    public static final byte WORLD_EVENT = -32;
    public static final byte WORLD_PARTICLES = -31;
    public static final byte LIGHT_UPDATE = -30;
    public static final byte LOGIN = -29;
    public static final byte MAP = -28;
    public static final byte OPEN_WINDOW_MERCHANT = -27;
    public static final byte REL_ENTITY_MOVE = -26;
    public static final byte REL_ENTITY_MOVE_LOOK = -25;
    public static final byte ENTITY_LOOK = -24;
    public static final byte ENTITY = -23;
    public static final byte VEHICLE_MOVE = -22;
    public static final byte OPEN_BOOK = -21;
    public static final byte OPEN_WINDOW = -20;
    public static final byte OPEN_SIGN_EDITOR = -19;
    public static final byte AUTO_RECIPE = -18;
    public static final byte ABILITIES = -17;
    public static final byte COMBAT_EVENT = -16;
    public static final byte PLAYER_INFO = -15;
    public static final byte LOOK_AT = -14;
    public static final byte POSITION = -13;
    public static final byte RECIPES = -12;
    public static final byte ENTITY_DESTROY = -11;
    public static final byte REMOVE_ENTITY_EFFECT = -10;
    public static final byte RESOURCE_PACK_SEND = -9;
    public static final byte RESPAWN = -8;
    public static final byte ENTITY_HEAD_ROTATION = -7;
    public static final byte SELECT_ADVANCEMENT_TAB = -6;
    public static final byte WORLD_BORDER = -5;
    public static final byte CAMERA = -4;
    public static final byte HELD_ITEM_SLOT = -3;
    public static final byte VIEW_CENTRE = -2;
    public static final byte VIEW_DISTANCE = -1;
    public static final byte SCOREBOARD_DISPLAY_OBJECTIVE = 0;
    public static final byte ENTITY_METADATA = 1;
    public static final byte ATTACH_ENTITY = 2;
    public static final byte ENTITY_VELOCITY = 3;
    public static final byte ENTITY_EQUIPMENT = 4;
    public static final byte EXPERIENCE = 5;
    public static final byte UPDATE_HEALTH = 6;
    public static final byte SCOREBOARD_OBJECTIVE = 7;
    public static final byte MOUNT = 8;
    public static final byte SCOREBOARD_TEAM = 9;
    public static final byte SCOREBOARD_SCORE = 10;
    public static final byte SPAWN_POSITION = 11;
    public static final byte UPDATE_TIME = 12;
    public static final byte TITLE = 13;
    public static final byte ENTITY_SOUND = 14;
    public static final byte NAMED_SOUND_EFFECT = 15;
    public static final byte STOP_SOUND = 16;
    public static final byte PLAYER_LIST_HEADER_FOOTER = 17;
    public static final byte NBT_QUERY = 18;
    public static final byte COLLECT = 19;
    public static final byte ENTITY_TELEPORT = 20;
    public static final byte ADVANCEMENTS = 21;
    public static final byte UPDATE_ATTRIBUTES = 22;
    public static final byte ENTITY_EFFECT = 23;
    public static final byte RECIPE_UPDATE = 24;
    public static final byte TAGS = 25;
    public static final byte MAP_CHUNK_BULK = 26;
    public static final byte NAMED_ENTITY_SPAWN = 27;
    public static final byte PING = 29;
    public static final byte ADD_VIBRATION_SIGNAL = 30;
    public static final byte CLEAR_TITLES = 31;
    public static final byte INITIALIZE_BORDER = 32;
    public static final byte PLAYER_COMBAT_END = 33;
    public static final byte PLAYER_COMBAT_ENTER = 34;
    public static final byte PLAYER_COMBAT_KILL = 35;
    public static final byte SET_ACTIONBAR_TEXT = 36;
    public static final byte SET_BORDER_CENTER = 37;
    public static final byte SET_BORDER_LERP_SIZE = 38;
    public static final byte SET_BORDER_SIZE = 39;
    public static final byte SET_BORDER_WARNING_DELAY = 40;
    public static final byte SET_BORDER_WARNING_DISTANCE = 41;
    public static final byte SET_SUBTITLE_TEXT = 42;
    public static final byte SET_TITLES_ANIMATION = 43;
    public static final byte SET_TITLE_TEXT = 44;
    public static final byte SYSTEM_CHAT = 45;
    
    private static void load() {
        PacketType.access$700(PacketTypeClasses.Play.Server.SPAWN_ENTITY, (byte)(-67));
        PacketType.access$700(PacketTypeClasses.Play.Server.SPAWN_ENTITY_EXPERIENCE_ORB, (byte)(-66));
        PacketType.access$700(PacketTypeClasses.Play.Server.SPAWN_ENTITY_WEATHER, (byte)(-65));
        PacketType.access$700(PacketTypeClasses.Play.Server.SPAWN_ENTITY_LIVING, (byte)(-64));
        PacketType.access$700(PacketTypeClasses.Play.Server.SPAWN_ENTITY_PAINTING, (byte)(-63));
        PacketType.access$700(PacketTypeClasses.Play.Server.SPAWN_ENTITY_SPAWN, (byte)(-62));
        PacketType.access$700(PacketTypeClasses.Play.Server.ANIMATION, (byte)(-61));
        PacketType.access$700(PacketTypeClasses.Play.Server.STATISTIC, (byte)(-60));
        PacketType.access$700(PacketTypeClasses.Play.Server.BLOCK_BREAK, (byte)(-59));
        PacketType.access$700(PacketTypeClasses.Play.Server.BLOCK_BREAK_ANIMATION, (byte)(-58));
        PacketType.access$700(PacketTypeClasses.Play.Server.TILE_ENTITY_DATA, (byte)(-57));
        PacketType.access$700(PacketTypeClasses.Play.Server.BLOCK_ACTION, (byte)(-56));
        PacketType.access$700(PacketTypeClasses.Play.Server.BLOCK_CHANGE, (byte)(-55));
        PacketType.access$700(PacketTypeClasses.Play.Server.BOSS, (byte)(-54));
        PacketType.access$700(PacketTypeClasses.Play.Server.SERVER_DIFFICULTY, (byte)(-53));
        PacketType.access$700(PacketTypeClasses.Play.Server.CHAT, (byte)(-52));
        PacketType.access$700(PacketTypeClasses.Play.Server.MULTI_BLOCK_CHANGE, (byte)(-51));
        PacketType.access$700(PacketTypeClasses.Play.Server.TAB_COMPLETE, (byte)(-50));
        PacketType.access$700(PacketTypeClasses.Play.Server.COMMANDS, (byte)(-49));
        PacketType.access$700(PacketTypeClasses.Play.Server.TRANSACTION, (byte)(-48));
        PacketType.access$700(PacketTypeClasses.Play.Server.CLOSE_WINDOW, (byte)(-47));
        PacketType.access$700(PacketTypeClasses.Play.Server.WINDOW_ITEMS, (byte)(-46));
        PacketType.access$700(PacketTypeClasses.Play.Server.WINDOW_DATA, (byte)(-45));
        PacketType.access$700(PacketTypeClasses.Play.Server.SET_SLOT, (byte)(-44));
        PacketType.access$700(PacketTypeClasses.Play.Server.SET_COOLDOWN, (byte)(-43));
        PacketType.access$700(PacketTypeClasses.Play.Server.CUSTOM_PAYLOAD, (byte)(-42));
        PacketType.access$700(PacketTypeClasses.Play.Server.CUSTOM_SOUND_EFFECT, (byte)(-41));
        PacketType.access$700(PacketTypeClasses.Play.Server.KICK_DISCONNECT, (byte)(-40));
        PacketType.access$700(PacketTypeClasses.Play.Server.ENTITY_STATUS, (byte)(-39));
        PacketType.access$700(PacketTypeClasses.Play.Server.EXPLOSION, (byte)(-38));
        PacketType.access$700(PacketTypeClasses.Play.Server.UNLOAD_CHUNK, (byte)(-37));
        PacketType.access$700(PacketTypeClasses.Play.Server.GAME_STATE_CHANGE, (byte)(-36));
        PacketType.access$700(PacketTypeClasses.Play.Server.OPEN_WINDOW_HORSE, (byte)(-35));
        PacketType.access$700(PacketTypeClasses.Play.Server.KEEP_ALIVE, (byte)(-34));
        PacketType.access$700(PacketTypeClasses.Play.Server.MAP_CHUNK, (byte)(-33));
        PacketType.access$700(PacketTypeClasses.Play.Server.WORLD_EVENT, (byte)(-32));
        PacketType.access$700(PacketTypeClasses.Play.Server.WORLD_PARTICLES, (byte)(-31));
        PacketType.access$700(PacketTypeClasses.Play.Server.LIGHT_UPDATE, (byte)(-30));
        PacketType.access$700(PacketTypeClasses.Play.Server.LOGIN, (byte)(-29));
        PacketType.access$700(PacketTypeClasses.Play.Server.MAP, (byte)(-28));
        PacketType.access$700(PacketTypeClasses.Play.Server.OPEN_WINDOW_MERCHANT, (byte)(-27));
        PacketType.access$700(PacketTypeClasses.Play.Server.REL_ENTITY_MOVE, (byte)(-26));
        PacketType.access$700(PacketTypeClasses.Play.Server.REL_ENTITY_MOVE_LOOK, (byte)(-25));
        PacketType.access$700(PacketTypeClasses.Play.Server.ENTITY_LOOK, (byte)(-24));
        PacketType.access$700(PacketTypeClasses.Play.Server.ENTITY, (byte)(-23));
        PacketType.access$700(PacketTypeClasses.Play.Server.VEHICLE_MOVE, (byte)(-22));
        PacketType.access$700(PacketTypeClasses.Play.Server.OPEN_BOOK, (byte)(-21));
        PacketType.access$700(PacketTypeClasses.Play.Server.OPEN_WINDOW, (byte)(-20));
        PacketType.access$700(PacketTypeClasses.Play.Server.OPEN_SIGN_EDITOR, (byte)(-19));
        PacketType.access$700(PacketTypeClasses.Play.Server.AUTO_RECIPE, (byte)(-18));
        PacketType.access$700(PacketTypeClasses.Play.Server.ABILITIES, (byte)(-17));
        PacketType.access$700(PacketTypeClasses.Play.Server.COMBAT_EVENT, (byte)(-16));
        PacketType.access$700(PacketTypeClasses.Play.Server.PLAYER_INFO, (byte)(-15));
        PacketType.access$700(PacketTypeClasses.Play.Server.LOOK_AT, (byte)(-14));
        PacketType.access$700(PacketTypeClasses.Play.Server.POSITION, (byte)(-13));
        PacketType.access$700(PacketTypeClasses.Play.Server.RECIPES, (byte)(-12));
        PacketType.access$700(PacketTypeClasses.Play.Server.ENTITY_DESTROY, (byte)(-11));
        PacketType.access$700(PacketTypeClasses.Play.Server.REMOVE_ENTITY_EFFECT, (byte)(-10));
        PacketType.access$700(PacketTypeClasses.Play.Server.RESOURCE_PACK_SEND, (byte)(-9));
        PacketType.access$700(PacketTypeClasses.Play.Server.RESPAWN, (byte)(-8));
        PacketType.access$700(PacketTypeClasses.Play.Server.ENTITY_HEAD_ROTATION, (byte)(-7));
        PacketType.access$700(PacketTypeClasses.Play.Server.SELECT_ADVANCEMENT_TAB, (byte)(-6));
        PacketType.access$700(PacketTypeClasses.Play.Server.WORLD_BORDER, (byte)(-5));
        PacketType.access$700(PacketTypeClasses.Play.Server.CAMERA, (byte)(-4));
        PacketType.access$700(PacketTypeClasses.Play.Server.HELD_ITEM_SLOT, (byte)(-3));
        PacketType.access$700(PacketTypeClasses.Play.Server.VIEW_CENTRE, (byte)(-2));
        PacketType.access$700(PacketTypeClasses.Play.Server.VIEW_DISTANCE, (byte)(-1));
        PacketType.access$700(PacketTypeClasses.Play.Server.SCOREBOARD_DISPLAY_OBJECTIVE, (byte)0);
        PacketType.access$700(PacketTypeClasses.Play.Server.ENTITY_METADATA, (byte)1);
        PacketType.access$700(PacketTypeClasses.Play.Server.ATTACH_ENTITY, (byte)2);
        PacketType.access$700(PacketTypeClasses.Play.Server.ENTITY_VELOCITY, (byte)3);
        PacketType.access$700(PacketTypeClasses.Play.Server.ENTITY_EQUIPMENT, (byte)4);
        PacketType.access$700(PacketTypeClasses.Play.Server.EXPERIENCE, (byte)5);
        PacketType.access$700(PacketTypeClasses.Play.Server.UPDATE_HEALTH, (byte)6);
        PacketType.access$700(PacketTypeClasses.Play.Server.SCOREBOARD_OBJECTIVE, (byte)7);
        PacketType.access$700(PacketTypeClasses.Play.Server.MOUNT, (byte)8);
        PacketType.access$700(PacketTypeClasses.Play.Server.SCOREBOARD_TEAM, (byte)9);
        PacketType.access$700(PacketTypeClasses.Play.Server.SCOREBOARD_SCORE, (byte)10);
        PacketType.access$700(PacketTypeClasses.Play.Server.SPAWN_POSITION, (byte)11);
        PacketType.access$700(PacketTypeClasses.Play.Server.UPDATE_TIME, (byte)12);
        PacketType.access$700(PacketTypeClasses.Play.Server.TITLE, (byte)13);
        PacketType.access$700(PacketTypeClasses.Play.Server.ENTITY_SOUND, (byte)14);
        PacketType.access$700(PacketTypeClasses.Play.Server.NAMED_SOUND_EFFECT, (byte)15);
        PacketType.access$700(PacketTypeClasses.Play.Server.STOP_SOUND, (byte)16);
        PacketType.access$700(PacketTypeClasses.Play.Server.PLAYER_LIST_HEADER_FOOTER, (byte)17);
        PacketType.access$700(PacketTypeClasses.Play.Server.NBT_QUERY, (byte)18);
        PacketType.access$700(PacketTypeClasses.Play.Server.COLLECT, (byte)19);
        PacketType.access$700(PacketTypeClasses.Play.Server.ENTITY_TELEPORT, (byte)20);
        PacketType.access$700(PacketTypeClasses.Play.Server.ADVANCEMENTS, (byte)21);
        PacketType.access$700(PacketTypeClasses.Play.Server.UPDATE_ATTRIBUTES, (byte)22);
        PacketType.access$700(PacketTypeClasses.Play.Server.ENTITY_EFFECT, (byte)23);
        PacketType.access$700(PacketTypeClasses.Play.Server.RECIPE_UPDATE, (byte)24);
        PacketType.access$700(PacketTypeClasses.Play.Server.TAGS, (byte)25);
        PacketType.access$700(PacketTypeClasses.Play.Server.MAP_CHUNK_BULK, (byte)26);
        PacketType.access$700(PacketTypeClasses.Play.Server.NAMED_ENTITY_SPAWN, (byte)27);
        PacketType.access$700(PacketTypeClasses.Play.Server.PING, (byte)29);
        PacketType.access$700(PacketTypeClasses.Play.Server.ADD_VIBRATION_SIGNAL, (byte)30);
        PacketType.access$700(PacketTypeClasses.Play.Server.CLEAR_TITLES, (byte)31);
        PacketType.access$700(PacketTypeClasses.Play.Server.INITIALIZE_BORDER, (byte)32);
        PacketType.access$700(PacketTypeClasses.Play.Server.PLAYER_COMBAT_END, (byte)33);
        PacketType.access$700(PacketTypeClasses.Play.Server.PLAYER_COMBAT_ENTER, (byte)34);
        PacketType.access$700(PacketTypeClasses.Play.Server.PLAYER_COMBAT_KILL, (byte)35);
        PacketType.access$700(PacketTypeClasses.Play.Server.SET_ACTIONBAR_TEXT, (byte)36);
        PacketType.access$700(PacketTypeClasses.Play.Server.SET_BORDER_CENTER, (byte)37);
        PacketType.access$700(PacketTypeClasses.Play.Server.SET_BORDER_LERP_SIZE, (byte)38);
        PacketType.access$700(PacketTypeClasses.Play.Server.SET_BORDER_SIZE, (byte)39);
        PacketType.access$700(PacketTypeClasses.Play.Server.SET_BORDER_WARNING_DELAY, (byte)40);
        PacketType.access$700(PacketTypeClasses.Play.Server.SET_BORDER_WARNING_DISTANCE, (byte)41);
        PacketType.access$700(PacketTypeClasses.Play.Server.SET_SUBTITLE_TEXT, (byte)42);
        PacketType.access$700(PacketTypeClasses.Play.Server.SET_TITLES_ANIMATION, (byte)43);
        PacketType.access$700(PacketTypeClasses.Play.Server.SET_TITLE_TEXT, (byte)44);
        PacketType.access$700(PacketTypeClasses.Play.Server.SYSTEM_CHAT, (byte)45);
    }
    
    public static class Util
    {
        public static boolean isInstanceOfEntity(final byte packetID) {
            return packetID == -23 || packetID == -26 || packetID == -25 || packetID == -24;
        }
    }
}
